### PR TITLE
Convenience methods for Message

### PR DESCRIPTION
**Pull request by sempervictus**
Adds four public functions to Message objects:
1. msh - gets a cloned+owned copy of the MshSegment
2. generic_segments - gets cloned+owned copies all of the generic segments into a vec
3. generic_segments_by_name - same as `generic_segments` except filtering the results by matching the first element of each generic segment
4. clone - which clones the underlying source into a new Message and enabled to_owned()

Adds public method `segs_to_str_vecs` which creates `Vec<Vec<&'a str>>` out of vectors of` GenericSegment`s

### CODE REVIEW

**Comment by wokket** [comment]
Thanks for looking into this, it generally lgtm with a couple of nits:

- segments_by_name is cloning _all_ segments to only return a subset, can you tweak it to only clone the returned segments?
- a couple of simple unit tests (nothing crazy) to both show usage/make sure I don't regress them :)

**Comment by sempervictus** [comment]
Thanks for the feedback, adjusting

**Comment by sempervictus** [comment]
@wokket - ping for review please.

**Comment by sempervictus** [comment]
I think this is a logical block of work for a single PR - i have a history of stacking commits like oiled swine on long-lived PRs, so i'll try to keep it to just making sure _this_ functionality is proper :).

**Comment by wokket** [comment]
LGTM.  I'll have a double check locally, possibly make a couple of tweaks for small nits and then push a new version.

**Comment by sempervictus** [comment]
Thank you very much - will update my `Cargo.toml` once its up.

**Comment by wokket** [comment]
0.3.0  pushed to cargo.  Thanks for helping out.

**Pull request merged**
